name: Deploy to app
on:
  push:
    branches:
      - develop
    paths:
      - client/src/**
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: before test
        uses: ./.github/actions/validation
      - name: test
        run: |
          echo "${{ github.event.base_ref }}"
          echo "${{ github.ref_name }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"
          echo "${{ github.ref }}"
          echo "${{ github }}"
          echo "${GITHUB_REF#refs/heads/}"

          HEAD_REF=$(git rev-parse "origin/master")
          echo "${HEAD_REF}"
