name: Deploy to app
on:
  push:
    branches:
      - develop
    paths:
      - client/src/**
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check sha
        run: |
          HEAD_REF=$(git rev-parse origin/master)
          TAG_REF=$(git rev-parse "$GIT_TAG")

          echo {$HEAD_REF}
          echo {$TAG_REF}

          if [ "$TAG_REF" = "$HEAD_REF" ]; then
            echo "sha is OK"
          else
            echo "sha is NG"
            exit 1
          fi
      - name: test
        run: |
          echo "${{ github.event.base_ref }}"
          echo "${{ github.ref_name }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"
          echo "${{ github.ref }}"
          echo "${{ github }}"
          echo "${GITHUB_REF#refs/heads/}"

          HEAD_REF=$(git rev-parse "origin/master")
          echo "${HEAD_REF}"
